config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  root 'breweries#index'
  get 'all_beers', to: 'beers#index'
  # get 'ratings', to: 'ratings#index'
  # get 'ratings/new', to: 'ratings#new'
  # post 'ratings', to: 'ratings#create'
  
  resources :ratings, only: [:index, :new, :create, :destroy]

  get 'signup', to: 'users#new'

  resource :session, only: [:new, :create, :destroy]

  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :memberships, only: [:index, :new, :create, :destroy]

  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  include RatingAverage

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validate :year_is_less_than_or_equal_to_current_year
  validates :name, presence: true
  validates :year, numericality: {
    greater_than_or_equal_to: 1040,
    only_integer: true
  }

  def year_is_less_than_or_equal_to_current_year
    return unless year > Date.today.year

    errors.add(:year, "can't be greater than current year")
  end

  def print_report
    puts name
    puts "established at year #{year}"
    puts "number of beers #{beers.count}"
  end

  def restart
    self.year = 2022
    puts "changed year to #{year}"
  end

  def to_s
    name.to_s
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: %i[show edit update destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /breweries or /breweries.json
  def index
    @breweries = Brewery.all
  end

  # GET /breweries/1 or /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries or /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: "Brewery was successfully created." }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1 or /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: "Brewery was successfully updated." }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1 or /breweries/1.json
  def destroy
    @brewery.destroy

    respond_to do |format|
      format.html { redirect_to breweries_path, status: :see_other, notice: "Brewery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def brewery_params
    params.require(:brewery).permit(:name, :year)
  end

  # def authenticate
  #   admin_accounts = { "pekka" => "beer", "arto" => "foobar", "matti" => "ittam", "vilma" => "kangas", "123456789" => "987654321" }

  #   authenticate_or_request_with_http_basic do |username, password|
  #     return true if (admin_accounts.key?(username) && admin_accounts[username] == password) || (username == "admin" && password == "secret")

  #     raise "Wrong username or password" # username/password was wrong
  #   end
  # end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_brewery.html.erb
<div id="<%= dom_id brewery %>">
  <h2>
    <strong> <%= brewery.name %> </strong>
  </h2>

  <p>
    <em>Established in: <%= brewery.year %></em>
    
  </p>

  <p>
    Number of beers: <%= @brewery.beers.count %>
  </p>

  <p>
    <% brewery.beers.each do |beer| %>
      <%= link_to beer.name, beer %>
    <% end %>
  </p>

  <p>
    <% if brewery.ratings.present? %>
    Brewery has <%= pluralize(brewery.ratings.count, 'rating') %> 
    with an average of <%= brewery.average_rating %>
    <% end %>
  </p>

</div>

app/views/breweries/_form.html.erb
<%= form_with(model: brewery) do |form| %>
  <% if brewery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
        <% brewery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/breweries/breweries.html.erb
<%= @breweries.count %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Show this brewery", @brewery %> |
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Breweries</h1>

<p>Number of breweries: <%= @breweries.count %></p>

<div id="breweries">
  <% @breweries.each do |brewery| %>
    <div id="<%= dom_id brewery %>">
      <p>
        <%= link_to brewery.name, brewery %>
      </p>

      <p>
        <strong>Year:</strong>
        <%= brewery.year %>
      </p>

    </div>
  <% end %>
</div>

<%= link_to "New brewery", new_brewery_path if current_user%>

<%= link_to "list of beers", beers_path %>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render "form", brewery: @brewery %>

<br>

<div>
  <%= link_to "Back to breweries", breweries_path %>
</div>

app/views/breweries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @brewery %>

<div>
  <%= link_to "Edit this brewery", edit_brewery_path(@brewery) if current_user%> |
  <%= link_to "Back to breweries", breweries_path %>

  <%= button_to "Destroy this brewery", @brewery, method: :delete if current_user %>
</div>