config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  
  root 'breweries#index'
  get 'all_beers', to: 'beers#index'
  # get 'ratings', to: 'ratings#index'
  # get 'ratings/new', to: 'ratings#new'
  # post 'ratings', to: 'ratings#create'
  
  resources :ratings, only: [:index, :new, :create, :destroy]

  get 'signup', to: 'users#new'

  resource :session, only: [:new, :create, :destroy]

  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :memberships, only: [:index, :new, :create, :destroy]

  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navibar">
      <%= link_to 'breweries', breweries_path %>
      <%= link_to 'beers', beers_path %>
      <%= link_to 'ratings', ratings_path %>
      <%= link_to 'users', users_path %>
      <%= link_to 'clubs', beer_clubs_path %>
      <%= link_to 'places', places_path %>
      <%= link_to 'styles', styles_path %>
      |
      <% if current_user %>
        <%= link_to current_user.username, current_user %>
        <%= link_to 'Rate a new beer', new_rating_path %>
        <%= link_to 'Join a club', new_membership_path %>
        <%= link_to 'Sign Out', session_path,
        data: {
          "turbo-method": :delete
        }, class: "link-secondary smooth" %>
      <% else %>
        <%= link_to 'Sign Up', signup_path %>
        <%= link_to 'Sign In', signin_path %>
      <% end %>
    </div>

    <% if current_user %>
      <p><%= current_user.username %> signed in</p>
    <% end %>

    <%= yield %>
  </body>
</html>